### ISSUE TITLE
Auto Populate Controls  - table fields default value

### ISSUE THREAD

**Issue by tplevrak** [lazymofo/datagrid#70]
Dear Ian,

I have a question regarding the population of table fields default values in a record when i make a new record through lazymofo.

I remember this was working, but now i have a grid and it does not work.

I have $lm->auto_populate_controls = true;, which is also the default of course, but it does not get any default values and all fields are null.

Is there something that i am missing ?

Is there something that disables auto_populate_controls behaviour ?

Thank you for your time

Best regards.

**Comment by lazymofo** [comment]
I just tested and noticed a bug where quotes were added to default strings.
I'll fix that soon.

The auto_populate_controls flag just populates the following:

form_default_value (database default value that can be overridden)
and
form_input_control (type of field, text, date, etc)

You can print these 2 arrays after calling the run() method.

I'm not sure what your issue is, but I assume form_default_value is NOT
getting populated.
You might want to see if your user can access information_schema.columns.
It's probably a permissions issue.

try adding this at the bottom after run()
print_r($lm->query('select * from information_schema.columns'));

No output means your user can't access the meta data.

You could also hard code the defaults in the script:
$lm->form_default_value['market_name'] = 'my default';










auto_populate_controls is to populate form_input_control and
grid_input_control.
 It detects types like date, textarea, checkbox flags.

For populating database defaults on the form add fields to
$lm->form_default_value

$lm->form_default_value["market_name"] = "my market";
or
$lm->form_default_value["market_name"] = null; // pull value from database
default

**Comment by tplevrak** [comment]
Dear Ian,

Thank you very much about the immediate response.

When i placed
print_r($lm->query('select * from information_schema.columns'));
after lazymofo run, i got a lot of output so obviously it is not a permissions issue.

You said that
_The auto_populate_controls flag just populates the following:

form_default_value (database default value that can be overridden)
and
form_input_control (type of field, text, date, etc)_

well the form_default_value (database default value that can be overridden) is not working for me or it is somehow overridden.

I can not figure out why.

But your suggestion about using $lm->form_default_value works perfectly and although it does require a bit more work it gives me the control over the default values i need. I must have somehow overlooked it and i was unaware of its existence.

So, Thanks again for your help. and Best Regards.
