### ISSUE TITLE
Extra column values needed for Custom output control conditionally formatted

### ISSUE THREAD

**Issue by tplevrak** [lazymofo/datagrid#94]
Dear Ian,

I hope that you are well and happy in your life.

I wanted to ask you about another feature for conditional formatting of a field.

As per Issues 26 and 71 i can create a custom output field so that i can format it in a custom way.
But i would like in the function to be able to use values from other columns in the grid.
(e.g. i have a column that the  text color is mentioned in another column of the grid)

Right now i can do this, by having a concatenated column with the two column values in the grid as the custom one 
And in the function  i separate the concatenated values with string manipulation and i finally get the values for multiple columns to form my final return value.

But it looks like it is too much trouble especially if i want more than two column values

Is it possible to be done in a more clean and easy way ?

Best Regards

**Comment by lazymofo** [comment]
If I understand you, typically I do something like this in your case:
If your database supports it, use json_object() instead of concat_ws().

$lm-grid_sql = "
select
color
, concat_ws('|', color, name) as color_and_name
from table";

$lm->form_input_control['color_and_name'] = array("type" =>
"color_and_name");

function color_and_name($column_name, $value, $command, $called_from){

    $arr = explode('|', $value);

    global $lm;
    $color = $lm->clean_out($arr[0]);
    $name = $lm->clean_out($arr[1]);
    return "<div style='color: $color'>$name</div>";

}

**Comment by tplevrak** [comment]
Ian,

Thank you very much for your response and sorry i was late to respond.

Your solution is surely more elegant than mine and a lot less time consuming if there are more than 2 columns to use their value.

Thanks Again !!!

Best Regards
